#!/bin/sh

ROOTDIR=`pwd`
export ROOTDIR=$ROOTDIR

cp linux-3.4.x/.config config.linux
cp user/busybox/busybox-1.24.x/.config config.busybox 

if [ ! -f "$ROOTDIR/.config" ] ; then
	cp -fv "$ROOTDIR/configs/templates/n56u_dlna.config" "$ROOTDIR/.config"
fi

if [ ! -f "$ROOTDIR/.config" ] ; then
	echo "Project config file .config not found! Terminate."
	exit 1
fi

echo "-------------CLEAN-ALL---------------"
rm -rf $ROOTDIR/stage
make clean

rm -rfv $ROOTDIR/romfs
rm -rfv $ROOTDIR/images
rm -rfv $ROOTDIR/stage

cp config.busybox  user/busybox/busybox-1.24.x/.config
cp config.linux linux-3.4.x/.config
