#!/bin/sh

DaleyTime=1
NET_INTERFACE="eth2.2"

str=0
RX_NOW=0;RX_PRE=0;
RX_SPEED=0;RX_COUNT=0;
RX_SPEED_K=0;RX_COUNT_M=0;

TX_NOW=0;TX_PRE=0;
TX_SPEED=0;TX_COUNT=0;
TX_SPEED_K=0;
TX_COUNT_M=0;

show_dec()
{
        #echo 'dec:'$1
        rdec=$(($1/100))
        echo $rdec
}

show_k()
{
    intk=0
    dec=0
    intk=$(( $1 / 1024 ))
    dec=$(( ($1 - intk * 1024) * 1000 / 1024))
    #echo '[' $dec ']'

    if [ "$intk" -ge 100 ]; then
        echo $intk.`show_dec $dec`
    elif [ "$intk" -ge 10 ]; then
        echo ' '$intk.`show_dec $dec`
    else
        echo  '. '${intk}.`show_dec $dec`
    fi
}

show_m()
{
    val=$(( $1/1024))
    show_k $val

}

if [ "$1" != "" ]
then
        NET_INTERFACE=$1
        if [ "$2" != "" ]
        then
                DaleyTime=$2
        fi
fi

#str=`/sbin/ifconfig $NET_INTERFACE | grep 'RX packets' `
str=`cat /proc/net/dev | grep $NET_INTERFACE`

if [ "$str" = "" ]
then
	echo "interface:$NET_INTERFACE is not exist. exit"
	exit 0
fi

#Inter-|   Receive                                                |  Transmit
# face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
#enp5s0: 3809       88379   0 8352    0     0          0  41200539 3992      7368    0    0    0     0       0          0

#echo $str
RX_NOW=`echo $str | awk '{printf $2}' `

RX_PRE=$RX_NOW

#echo $RX_NOW && exit 0;

#str=`/sbin/ifconfig $NET_INTERFACE | grep 'TX packets' `
TX_NOW=`echo $str | awk '{printf $10}' `
TX_PRE=$TX_NOW

#echo "$RX_NOW -- $TX_NOW" && exit 0;

sleep $DaleyTime

#echo $TX_PRE
#exit 0;

while :
do
        str=`cat /proc/net/dev | grep $NET_INTERFACE `
        RX_NOW=`echo $str | awk '{printf $2}' `
                
        #echo "$RX_NOW $RX_PRE $RX_SPEED"
        RX_SPEED=$(( $RX_NOW - $RX_PRE ))


        #echo echo $RX_SPEED
        RX_SPEED=$(($RX_SPEED/$DaleyTime))

        TX_NOW=`echo $str | awk '{printf $10}' `
                #echo  $TX_NOW-$TX_PRE-$DaleyTime
        TX_SPEED=$(( ($TX_NOW-$TX_PRE)/$DaleyTime ))

        #echo $RX_SPEED '     ' $TX_SPEED
        echo $NET_INTERFACE: RXSpeed:`show_k $RX_SPEED`k/s RX Count:`show_m $RX_NOW`M '|' TXSpeed:`show_k $TX_SPEED`k/s TX Count:`show_m $TX_NOW`M ' ' `date +%T`  #.%N

        sleep $DaleyTime
        RX_PRE=$RX_NOW
        TX_PRE=$TX_NOW
done